# Generated by Django 5.2.6 on 2026-03-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admission Form', 'verbose_name_plural': 'Admission Forms'},
        ),
        migrations.AlterField(
            model_name='admission',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
